name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: apt-get update -y && apt-get upgrade -y
      run: pip3 install -U pip
      run: pip3 install -U -r requirements.txt
      run: python3 -m RADHIKA
